/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app_kepega;

import Kelas.Pegawai;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Kelas.Pegawai;
import javax.swing.JOptionPane;

/**
 *
 * @author Good_Poeple
 */
public class DataPegawai extends javax.swing.JPanel {

    /**
     * Creates new form DataPegawai
     */
    public DataPegawai() {
        initComponents();
        loadTable();
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String keyword = txtCari.getText().trim(); // Ambil teks pencarian
                cariPegawai(keyword); // Panggil metode pencarian
            }
        });
    }

    void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Dosen");
        model.addColumn("Nama Dosen");
        model.addColumn("NIDN");
        model.addColumn("Email");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Status");

        try {
            Pegawai pg = new Pegawai();
            ResultSet data = pg.tampilPegawai();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("dosen_id"),
                    data.getString("dosen_nama"),
                    data.getString("dosen_nidn"),
                    data.getString("dosen_email"),
                    data.getString("dosen_telepon"),
                    data.getString("dosen_alamat"),
                    data.getString("masuk_tanggal"),
                    data.getString("status"),});

            }

        } catch (SQLException sQLException) {

        }

        tblPegawai.setModel(model);
    }

    void cariPegawai(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Dosen");
        model.addColumn("Nama Dosen");
        model.addColumn("NIDN");
        model.addColumn("Email");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Status");

        try {
            Pegawai pg = new Pegawai(); // Instansiasi kelas Pegawai
            ResultSet data = pg.cariPegawai(keyword); // Panggil metode dari kelas Pegawai

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("dosen_id"),
                    data.getString("dosen_nama"),
                    data.getString("dosen_nidn"),
                    data.getString("dosen_email"),
                    data.getString("dosen_telepon"),
                    data.getString("dosen_alamat"),
                    data.getDate("masuk_tanggal"), // Untuk kolom Date
                    data.getString("status")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        tblPegawai.setModel(model); // Set hasil pencarian ke tabel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Pegawai");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari");

        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPegawai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TambahPegawai tambahpegawai = new TambahPegawai();
        tambahpegawai.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegawaiMouseClicked
        try {
        int baris = tblPegawai.rowAtPoint(evt.getPoint());
        if (baris >= 0) { // Pastikan baris valid
            String ID = tblPegawai.getValueAt(baris, 0) != null ? tblPegawai.getValueAt(baris, 0).toString() : "";
            String Nama = tblPegawai.getValueAt(baris, 1) != null ? tblPegawai.getValueAt(baris, 1).toString() : "";
            String NIDN = tblPegawai.getValueAt(baris, 2) != null ? tblPegawai.getValueAt(baris, 2).toString() : "";
            String email = tblPegawai.getValueAt(baris, 3) != null ? tblPegawai.getValueAt(baris, 3).toString() : "";
            String tlp = tblPegawai.getValueAt(baris, 4) != null ? tblPegawai.getValueAt(baris, 4).toString() : "";
            String alamat = tblPegawai.getValueAt(baris, 5) != null ? tblPegawai.getValueAt(baris, 5).toString() : "";
            String tanggal = tblPegawai.getValueAt(baris, 6) != null ? tblPegawai.getValueAt(baris, 6).toString() : "";
            String status = tblPegawai.getValueAt(baris, 7) != null ? tblPegawai.getValueAt(baris, 7).toString() : "";

            // Membuka FrameBarang dan mengirimkan data
            TambahPegawai tp = new TambahPegawai();
            tp.setData(ID, Nama,NIDN, email, tlp, alamat, tanggal, status);
            tp.setVisible(true);
            
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memilih data: " + ex.getMessage());
    } finally {
       // isTableSelection = false; // Selesai seleksi dari tabel
    }
    }//GEN-LAST:event_tblPegawaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPegawai;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
